# This is a basic workflow to help you get started with Actions
name: Update epics
on:
  issues:
    types: [opened, created, closed, reopened, deleted]
jobs:
  epics:
    runs-on: main
    name: Update epic issues
    steps:
      - name: Run epics action
        uses: cloudaper/epics-action@v1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          epic-label-name: epic
